name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Upload to S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Copy files to S3 with the AWS CLI
      run: |
        aws s3 sync . s3://javiscoffee.com
      
  cache:
    name: Invalidate Cache
    runs-on: ubuntu-latest

    steps:
    - name: Invalidate cloudfront distribution and wait for completion
      uses: muratiger/invalidate-cloudfront-and-wait-for-completion-action@master
      env:
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
        PATHS: '/*'
        AWS_REGION: ${{ secrets.CF_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  notify:
    name: Notify Me
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#57dd3c'
        SLACK_TITLE: Deploy to Production SUCCESSFUL
        SLACK_USERNAME: GitHub Actions

  audit:
    name: Audit with Lighthouse
    runs-on: ubuntu-latest
    
    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://jarv.is/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'

    - name: Audit Netlify deploy preview
      uses: jakejarvis/lighthouse-action@master
      with:
        netlify_site: ${{ secrets.NETLIFY_SITE }}
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
  