name: Stage

on:
  push:
    branches:
      - dev

jobs:
  lighthouse:
    name: Audit with Lighthouse
    runs-on: ubuntu-latest

    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://jarv.is/'

    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'

  notify:
    name: Notify Me
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#57dd3c'
        SLACK_TITLE: Deploy to Stage SUCCESSFUL
        SLACK_USERNAME: GitHub Actions
    
  