name: Stage

on:
  push:
    branches:
      - dev

jobs:
  netlify:
    name: Deploy to Netlify
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Check changes in stories
      uses: netlify/actions/diff-includes@master
      with:
        args: docs

  lighthouse:
    name: Audit with Lighthouse
    runs-on: ubuntu-latest

    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://jarv.is/'

    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
    
  