name: Build & Test

on:
  push:
    branches:
      - dev

jobs:
  lighthouse:
    name: Audit with Lighthouse
    runs-on: ubuntu-latest

    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://jarv.is/'

    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
    
  netlify:
    name: Deploy to Netlify
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Upload to Netlify
      uses: jsmrcaga/action-netlify-deploy@master
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
        NETLIFY_DEPLOY_TO_PROD: true
  