name: Build & Test

on:
  push:
    branches:
      - dev

jobs:
  lighthouse:
    name: Audit with Lighthouse
    runs-on: ubuntu-latest

    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://jarv.is/'

    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
  
  webPageTest:
    name: Run a WebPagetest
    runs-on: ubuntu-latest
    
    steps:
      - uses: JCofman/webPagetestAction@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_URL: ${{ secrets.TEST_URL }}
          WEBPAGETEST_API_KEY: ${{ secrets.WEBPAGETEST_API_KEY }}