name: Build & Test

on:
  push:
    branches:
      - dev

jobs:
  lighthouse:
    name: Audit with Lighthouse
    runs-on: ubuntu-latest

    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://jarv.is/'

    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
  
    netlify:
      name: Build Netlify site    
      runs-on: ubuntu-latest     
        
      steps:
        - name: Audit Netlify deploy preview
          uses: jakejarvis/lighthouse-action@master
          with:
            netlify_site: ${{ secrets.NETLIFY_SITE }}
        - name: Create artifact
        - uses: actions/upload-artifact@master
          with:
            name: report
            path: './report'